Fix/autoplay documentation#82
appleple/react-modal-video pull request #93
Opened 2023-06-20 08:49 UTC by 1000-x-t30

2023-06-22 07:57 UTC, uidev1116 requested changes
@1000-x-t30 
気になったところコメントさせていただきました。🙇
ご確認よろしくお願いします。！！

2023-06-22 07:57 UTC, uidev1116 commented on src/index.jsx
> -            <div className={this.props.classNames.modalVideo} tabIndex='-1' role='dialog'
@1000-x-t30 
tabIndex='-1' は削除しないほうが良いかと思います。`this.modal.focus()` でフォーカスできなくなってしまうためです。いかがでしょうか？

2023-06-22 07:57 UTC, uidev1116 commented on src/index.jsx
> +                    <button className={this.props.classNames.modalVideoCloseBtn} aria-label={this.props.aria.dismissBtnMessage} ref={(node) => { this.modalbtn = node; }} onKeyDown={this.updateFocus}
@1000-x-t30 
あくまで僕の意見なので、修正が必要というわけではないですが、 tabIndexに 2 の指定はあまりしないかもです。
[MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/tabindex)でも以下のように書かれていますので、tabIndexに -1 or 0 以外の値は指定しないほうが無難な気がします。

> 警告: tabindex の値として、0 と -1 のみを使用することをお勧めします。tabindex の値を 0 より大きくしたり、フォーカス可能な HTML 要素の順序を変更できる CSS プロパティ（[フレックスアイテムの並べ替え](https://developer.mozilla.org/ja/docs/Web/CSS/CSS_flexible_box_layout/Ordering_flex_items)）を使用したりしないようにしましょう。これは、キーボードによるナビゲーションや支援技術を使用している人にとって、ページのコンテンツを操作することが難しくなります。代わりに、論理的な順序で要素を記述してください。

2023-06-22 07:57 UTC, uidev1116 commented on src/index.jsx
> +    mute: 1
@1000-x-t30 
デフォルト値を変更する意図がよくわかってないのですが、なにかありますでしょうか？
今まで利用してくれていた方にとってはアップデートしたら急に動作が変わった！となって困ってしまうように思えます…🫠

ご確認よろしくお願いします。🫡

2023-06-22 07:57 UTC, uidev1116 commented on src/index.jsx
> +  updateFocus(e) {
@1000-x-t30 
#79 の原因ですが、 `updateFocus` メソッドで `this.modal` と `this.modalbtn` を順番にフォーカスしてるのが原因な気がしてます。😵‍💫

2023-06-26 01:29 UTC, 1000-x-t30 commented on src/index.jsx
> +    mute: 1
@uidev1116
Google Chromeでは、ミュートにしてないとオートプレイされない仕様に変更されたからです。元々オートプレイにされていたこと、Chromeのシェア率も考えて、優先したほうがいいのかなと考え変更したのですが、おっしゃる通り今まで利用して下さってた方々のことも考えると変更しないほうが良かったですね...
元に戻しておきます&#x1FAE1;

2023-06-26 05:46 UTC, 1000-x-t30 commented on src/index.jsx
> -            <div className={this.props.classNames.modalVideo} tabIndex='-1' role='dialog'
@uidev1116 
dialogタグを検討していたときに消えてしまっていたものと思います。
あった方が良かったので修正します...&#x1f647;

2023-06-26 05:47 UTC, 1000-x-t30 commented on src/index.jsx
> +                    <button className={this.props.classNames.modalVideoCloseBtn} aria-label={this.props.aria.dismissBtnMessage} ref={(node) => { this.modalbtn = node; }} onKeyDown={this.updateFocus}
@uidev1116 
調べが足りませんでした。ありがとうございます！！

2023-06-28 09:29 UTC, uidev1116 approved these changes
ありがとうございます。！ approve します。！

2023-06-28 09:29 UTC, merged